schemaVersion: 2.0.0
fileExistenceTests:
  - name: 'prometheus'
    path: '/home/app/bin/prometheus'
    shouldExist: true
    permissions: '-rwxr-xr-x'
  - name: 'promtool'
    path: '/home/app/bin/promtool'
    shouldExist: true
    permissions: '-rwxr-xr-x'
  - name: 'profile.d'
    path: '/home/app/.profile.d/prometheus.sh'
    shouldExist: true
    permissions: '-rw-r--r--'
fileContentTests:
- name: 'profile.d'
  path: '/home/app/.profile.d/prometheus.sh'
  expectedContents: ['export PATH=\$PATH:/home/app/bin']
